Terms are not compatible with solver! Got: ODETerm( vector_field=NeuralODE( func=Func( mlp=MLP( layers=( Linear( weight=f32[64,6](jax), bias=f32[64](jax), in_features=6, out_features=64, use_bias=True ), Linear( weight=f32[64,64](jax), bias=f32[64](jax), in_features=64, out_features=64, use_bias=True ), Linear( weight=f32[64,64](jax), bias=f32[64](jax), in_features=64, out_features=64, use_bias=True ), Linear( weight=f32[64,64](jax), bias=f32[64](jax), in_features=64, out_features=64, use_bias=True ), Linear( weight=f32[6,64](jax), bias=f32[6](jax), in_features=64, out_features=6, use_bias=True ) ), activation=<PjitFunction of <function softplus at 0xffff64d8b240>>, final_activation=<function <lambda>>, use_bias=True, use_final_bias=True, in_size=6, out_size=6, width_size=64, depth=4 ) ), rtol=1e-06, atol=1e-06 ) ) but expected: diffrax.AbstractTerm Note that terms are checked recursively: if you scroll up you may find a root-cause error that is more specific.

TypeError: NeuralODE.__call__() takes 3 positional arguments but 4 were given During handling of the above exception, another exception occurred: ValueError: Error while tracing ODETerm( vector_field=NeuralODE( func=Func( mlp=MLP( layers=( Linear( weight=f32[64,6], bias=f32[64], in_features=6, out_features=64, use_bias=True ), Linear( weight=f32[64,64], bias=f32[64], in_features=64, out_features=64, use_bias=True ), Linear( weight=f32[64,64], bias=f32[64], in_features=64, out_features=64, use_bias=True ), Linear( weight=f32[64,64], bias=f32[64], in_features=64, out_features=64, use_bias=True ), Linear( weight=f32[6,64], bias=f32[6], in_features=64, out_features=6, use_bias=True ) ), activation=<PjitFunction of <function softplus at 0xffff64d8b240>>, final_activation=<function <lambda>>, use_bias=True, use_final_bias=True, in_size=6, out_size=6, width_size=64, depth=4 ) ), rtol=1e-06, atol=1e-06 ) ).vf: NeuralODE.__call__() takes 3 positional arguments but 4 were given The above exception was the direct cause of the following exception: File "/workspaces/neuralODEs/neuralODE/scripts/experiments/compare_2D_trajectories.py", line 28, in run diffrax.ODETerm(self.model), diffrax.Tsit5(), t0=ts[0], t1=ts[-1], dt0=ts[1] - ts[0], y0=self.initial_conditions, stepsize_controller=diffrax.PIDController( rtol=rtol, atol=atol, ), saveat=diffrax.SaveAt(ts=ts), max_steps=10000, ) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/workspaces/neuralODEs/neuralODE/scripts/visualizers/CompareTrajectory2dVis.py", line 151, in main t_span, y_true, y_pred = experiment.run() ^^^^^^^^^^^^^^^^ File "/workspaces/neuralODEs/neuralODE/scripts/visualizers/CompareTrajectory2dVis.py", line 165, in <module> main() ValueError: Terms are not compatible with solver! Got: ODETerm( vector_field=NeuralODE( func=Func( mlp=MLP( layers=( Linear( weight=f32[64,6](jax), bias=f32[64](jax), in_features=6, out_features=64, use_bias=True ), Linear( weight=f32[64,64](jax), bias=f32[64](jax), in_features=64, out_features=64, use_bias=True ), Linear( weight=f32[64,64](jax), bias=f32[64](jax), in_features=64, out_features=64, use_bias=True ), Linear( weight=f32[64,64](jax), bias=f32[64](jax), in_features=64, out_features=64, use_bias=True ), Linear( weight=f32[6,64](jax), bias=f32[6](jax), in_features=64, out_features=6, use_bias=True ) ), activation=<PjitFunction of <function softplus at 0xffff64d8b240>>, final_activation=<function <lambda>>, use_bias=True, use_final_bias=True, in_size=6, out_size=6, width_size=64, depth=4 ) ), rtol=1e-06, atol=1e-06 ) ) but expected: diffrax.AbstractTerm Note that terms are checked recursively: if you scroll up you may find a root-cause error that is more specific.